// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcxtNGf85pYvmet4YOCPyx739foYy2708',
    appId: '1:634446441633:web:e1b6c7e6f3558717a3d4e0',
    messagingSenderId: '634446441633',
    projectId: 'qmbuddy-prod',
    authDomain: 'qmbuddy-prod.firebaseapp.com',
    storageBucket: 'qmbuddy-prod.firebasestorage.app',
    measurementId: 'G-5KBVGNJF0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-Eid7emPThBpaQ_PYV6eDL1hq8tCf0Q',
    appId: '1:634446441633:android:1bc203d7c0d6bd07a3d4e0',
    messagingSenderId: '634446441633',
    projectId: 'qmbuddy-prod',
    storageBucket: 'qmbuddy-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOeF50jqg8dRb8yvTArQXWzF7RpsWpg8Q',
    appId: '1:634446441633:ios:38845889c61f4d0fa3d4e0',
    messagingSenderId: '634446441633',
    projectId: 'qmbuddy-prod',
    storageBucket: 'qmbuddy-prod.firebasestorage.app',
    iosBundleId: 'com.md.qmbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOeF50jqg8dRb8yvTArQXWzF7RpsWpg8Q',
    appId: '1:634446441633:ios:c0b491e573bfae4ca3d4e0',
    messagingSenderId: '634446441633',
    projectId: 'qmbuddy-prod',
    storageBucket: 'qmbuddy-prod.firebasestorage.app',
    iosBundleId: 'com.example.qmbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcxtNGf85pYvmet4YOCPyx739foYy2708',
    appId: '1:634446441633:web:ba20c7a2a1761c67a3d4e0',
    messagingSenderId: '634446441633',
    projectId: 'qmbuddy-prod',
    authDomain: 'qmbuddy-prod.firebaseapp.com',
    storageBucket: 'qmbuddy-prod.firebasestorage.app',
    measurementId: 'G-FJ7XMJK9WF',
  );
}
