// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPaDz0GoTt-EdXgjEnWTBs0mQyGAxNRUQ',
    appId: '1:464428121122:web:7b9d51214c165ce58f5e7b',
    messagingSenderId: '464428121122',
    projectId: 'pranavfcm-2362b',
    authDomain: 'pranavfcm-2362b.firebaseapp.com',
    storageBucket: 'pranavfcm-2362b.firebasestorage.app',
    measurementId: 'G-K4R3TE51SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDec5MI3dSWNhPqsdfTRlj5MogBwhnFQwc',
    appId: '1:464428121122:android:f6c60cfb88cb860c8f5e7b',
    messagingSenderId: '464428121122',
    projectId: 'pranavfcm-2362b',
    storageBucket: 'pranavfcm-2362b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTuGl9ag8eaQokweABpwl2XGKVL7bD4lw',
    appId: '1:464428121122:ios:970c5fbbe48fa5f68f5e7b',
    messagingSenderId: '464428121122',
    projectId: 'pranavfcm-2362b',
    storageBucket: 'pranavfcm-2362b.firebasestorage.app',
    iosBundleId: 'com.md.qmbuddy.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTuGl9ag8eaQokweABpwl2XGKVL7bD4lw',
    appId: '1:464428121122:ios:69e4c1306ea76de18f5e7b',
    messagingSenderId: '464428121122',
    projectId: 'pranavfcm-2362b',
    storageBucket: 'pranavfcm-2362b.firebasestorage.app',
    iosBundleId: 'com.example.qmbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPaDz0GoTt-EdXgjEnWTBs0mQyGAxNRUQ',
    appId: '1:464428121122:web:ed24c4079155fae68f5e7b',
    messagingSenderId: '464428121122',
    projectId: 'pranavfcm-2362b',
    authDomain: 'pranavfcm-2362b.firebaseapp.com',
    storageBucket: 'pranavfcm-2362b.firebasestorage.app',
    measurementId: 'G-WB0QRC677N',
  );
}
